### ISSUE TITLE
.extend is not a function

### ISSUE THREAD

**Issue by OmgImAlexis** [visionmedia/debug#643]
I'm trying to run [the example](https://github.com/visionmedia/debug#extend) and for some reason the extend field is missing. I'm using node `v10.13.0`. I did notice this works fine on my other machine with node `v11.0.0`.

```console
root@Devon:/mnt/user/code/api# node
> const log = require('debug')('auth');
undefined
> const logSign = log.extend('sign');
TypeError: log.extend is not a function
> log
{ [Function: debug]
  namespace: 'auth',
  enabled: false,
  useColors: true,
  color: 3,
  inspectOpts: {} }
```

**Comment by OmgImAlexis** [comment]
Seems reinstalling it fixed this.

**Comment by amccloud** [comment]
@OmgImAlexis ran into the same problem with the same fix. Seems to multiple variants of debug installed and depending on the order you can end up with this?

**Comment by amccloud** [comment]
@Qix- In my case, we're using webpack, yarn, and link. So lots of complexity that can cause debug to get swapped with an older version

Do you have a recommended way for consolidating versions by chance? Right now we have about nine versions of debug in the project, eight installs are at version 2.x.x while my usage is at version 4.1

**Comment by Qix-** [comment]
No, this is an inherant problem with Node versioning and the fact that Debug is _really_ old.

**Comment by eddyw** [comment]
I've solve this by running `npm dedupe` first, then re-installing as dependency (note if it's `peerDependency` in your project, you need to manually install it as it won't be if just running `npm install`)

**Comment by Qix-** [comment]
`debug` should not be a `peerDependency`, ever. So yes, if it's listed as one, something is wrong 🙃
