### ISSUE TITLE
Debug crashes Heroku dyno

### ISSUE THREAD

**Issue by jhoogstraat** [visionmedia/debug#725]
I am getting a "cannot find module ./common" on Heroku, while it works on my local machine using 4.1.1

I looked into /node_modules on the dyno and indeed the common.js in the /src folder was missing. 

Edit: I just used the "deploy branch" option in the Heroku Dashboard. My config is really barebones:
```
{
  "name": "project",
  "version": "1.0.0",
  "engines": {
    "node": "12.4.0"
  },
  "description": "",
  "main": "server.js",
  "scripts": {
    "dev": "node -r dotenv/config server",
    "start": "node server"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.19.0",
    "axios-auth-refresh": "^1.0.7",
    "cheap-ruler": "^2.5.1",
    "debug": "^4.1.1",
    "dotenv": "^8.0.0",
    "express": "^4.17.1",
    "express-access-token": "^1.0.3",
    "geolib": "^3.0.4",
    "geolocation-utils": "^1.2.1",
    "mongoose": "^5.6.6",
    "supports-color": "^7.1.0"
  }
}
```

**Comment by Qix-** [comment]
Hi. You'd be the first of millions to not have this source file. Can you triple check whatever configuration (that you have not provided here, fwiw) is correct?

**Comment by Qix-** [comment]
Closing as there's not enough information.
